pipeline {
    agent {
        label ""
    }
    stages {
        stage("Preparation") {
            steps {
                sleep 2
                echo "We're not doing anything particularly special here."
            }
        }
    }
}